"""Official Python SDK for Noether — a decentralized perpetual exchange on Stellar / Soroban."""

from .client import NoetherClient
from .errors import (
    ApiError,
    AuthError,
    BadRequestError,
    ConflictError,
    ForbiddenError,
    NetworkError,
    NoetherError,
    NotFoundError,
    RateLimitError,
    RegionRestrictedError,
    ServerError,
    ServiceUnavailableError,
)
from .models import (
    AccountIdentity,
    AccountPositionsResponse,
    AccountShortfall,
    AccountVolume,
    AdlQueueResult,
    AdlQueueRow,
    AssetCapacity,
    AssetStats,
    BetaStatus,
    CandlePoint,
    CandlesResponse,
    HealthStatus,
    IssuedApiKey,
    IssuedChallenge,
    MarketStatsResponse,
    PoolCapacity,
    MarketSummary,
    OpenPositionRow,
    OracleAssetHealth,
    OracleHealth,
    OracleKeeperHealth,
    OracleOnchainHealth,
    OracleSnapshot,
    PreparedTransaction,
    RawEvent,
    ReferralBindingRow,
    ReferralClaimRow,
    ReferralMeResponse,
    ReferralTradeRow,
    ReferrerRow,
    SolvencyStats,
    SubmittedTx,
    TradeRow,
    VaultActivityRow,
    VaultRow,
    VaultTradeRow,
)

# Single source of truth for the package version — pyproject.toml reads
# this via [tool.hatch.version].
__version__ = "0.1.2"
__all__ = [
    "NoetherClient",
    # Errors
    "NoetherError",
    "ApiError",
    "AuthError",
    "ForbiddenError",
    "BadRequestError",
    "NotFoundError",
    "ConflictError",
    "RateLimitError",
    "RegionRestrictedError",
    "ServerError",
    "ServiceUnavailableError",
    "NetworkError",
    # Models
    "AccountIdentity",
    "AccountPositionsResponse",
    "AccountShortfall",
    "AccountVolume",
    "AdlQueueResult",
    "AdlQueueRow",
    "AssetCapacity",
    "AssetStats",
    "BetaStatus",
    "CandlePoint",
    "CandlesResponse",
    "HealthStatus",
    "IssuedApiKey",
    "IssuedChallenge",
    "MarketStatsResponse",
    "PoolCapacity",
    "MarketSummary",
    "OpenPositionRow",
    "OracleAssetHealth",
    "OracleHealth",
    "OracleKeeperHealth",
    "OracleOnchainHealth",
    "OracleSnapshot",
    "PreparedTransaction",
    "RawEvent",
    "ReferrerRow",
    "ReferralBindingRow",
    "ReferralClaimRow",
    "ReferralMeResponse",
    "ReferralTradeRow",
    "SolvencyStats",
    "SubmittedTx",
    "TradeRow",
    "VaultActivityRow",
    "VaultRow",
    "VaultTradeRow",
]
