-- Postgres baseline (Supabase migration, 2026-07).
--
-- Consolidates the retired SQLite migrations 001–017 into the current
-- schema. History: one-shot data fixes (006–009) and backfills (010/011)
-- are gone — data arrives via scripts/migrate-turso-to-supabase. Dead
-- tables positions_cache / orders_cache (schema-only since 001, zero
-- readers/writers — audit 2026-06 §340) are not carried over.
--
-- Type conventions (see docs/BACKUP_RESTORE.md):
--   * ledgers / unix timestamps / ids     → BIGINT
--     (api_keys.*_at are MILLISECONDS, event timestamps are seconds)
--   * chain i128 quantities written via .toString() and read via
--     BigInt(String(x)) / Number(x)       → TEXT (byte-parity with libsql)
--   * accumulators mutated in SQL (x=x+?) → NUMERIC (vaults, referrers)
--   * flags written as 0/1               → SMALLINT (vaults.paused)
--   * event payloads                     → JSONB, but ALWAYS read back as a
--     raw string (@noether/db pins json/jsonb type parsers to identity)
--
-- The runner executes one statement at a time: keep `--# split` between
-- statements (extended-protocol queries cannot batch statements).

CREATE TABLE IF NOT EXISTS poll_cursor (
  id                    INTEGER PRIMARY KEY CHECK (id = 1),
  last_ledger           BIGINT NOT NULL,
  last_pagination_token TEXT,
  updated_at            BIGINT NOT NULL
);

--# split

CREATE TABLE IF NOT EXISTS events_raw (
  event_id          TEXT PRIMARY KEY,
  contract_id       TEXT NOT NULL,
  topic             TEXT NOT NULL,
  ledger            BIGINT NOT NULL,
  ledger_close_ts   BIGINT NOT NULL,
  tx_hash           TEXT NOT NULL,
  payload_json      JSONB NOT NULL,
  inserted_at       BIGINT NOT NULL,
  topic_xdr         TEXT,
  value_xdr         TEXT
);

--# split

CREATE INDEX IF NOT EXISTS idx_events_topic_ledger ON events_raw (topic, ledger DESC);

--# split

CREATE INDEX IF NOT EXISTS idx_events_contract_ledger ON events_raw (contract_id, ledger DESC);

--# split

CREATE INDEX IF NOT EXISTS idx_events_ledger ON events_raw (ledger DESC);

--# split

-- liveTailer polls `WHERE inserted_at > $1` every second.
CREATE INDEX IF NOT EXISTS idx_events_inserted_at ON events_raw (inserted_at);

--# split

-- Serves the per-trader scans (account history, leaderboard, volume).
CREATE INDEX IF NOT EXISTS idx_events_payload_trader ON events_raw ((payload_json ->> 'trader'), ledger DESC);

--# split

-- Realized-trade projection (one row per close / liquidation / partial liq).
CREATE TABLE IF NOT EXISTS trades (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id      TEXT    NOT NULL UNIQUE,
  position_id   BIGINT  NOT NULL,
  trader        TEXT    NOT NULL,
  asset         TEXT    NOT NULL,
  direction     SMALLINT NOT NULL,
  kind          TEXT    NOT NULL,
  size          TEXT    NOT NULL,
  entry_price   TEXT,
  close_price   TEXT    NOT NULL,
  pnl           TEXT,
  ledger        BIGINT  NOT NULL,
  ts            BIGINT  NOT NULL,
  tx_hash       TEXT    NOT NULL,
  contract_id   TEXT    NOT NULL
);

--# split

CREATE INDEX IF NOT EXISTS idx_trades_asset_ts ON trades (asset, ts DESC);

--# split

CREATE INDEX IF NOT EXISTS idx_trades_trader_ts ON trades (trader, ts DESC);

--# split

CREATE TABLE IF NOT EXISTS candles (
  asset       TEXT NOT NULL,
  interval    TEXT NOT NULL,
  bucket_ts   BIGINT NOT NULL,
  open        BIGINT NOT NULL,
  high        BIGINT NOT NULL,
  low         BIGINT NOT NULL,
  close       BIGINT NOT NULL,
  volume      BIGINT NOT NULL,
  PRIMARY KEY (asset, interval, bucket_ts)
);

--# split

-- Open-position projection (rows deleted on close/liquidation).
CREATE TABLE IF NOT EXISTS positions (
  position_id     BIGINT   PRIMARY KEY,
  trader          TEXT     NOT NULL,
  asset           TEXT     NOT NULL,
  direction       SMALLINT NOT NULL,
  size            TEXT     NOT NULL,
  entry_price     TEXT     NOT NULL,
  opened_at       BIGINT   NOT NULL,
  opened_tx_hash  TEXT     NOT NULL,
  contract_id     TEXT
);

--# split

CREATE INDEX IF NOT EXISTS idx_positions_trader ON positions (trader);

--# split

CREATE TABLE IF NOT EXISTS api_keys (
  key_id          TEXT PRIMARY KEY,
  secret_hash     TEXT NOT NULL,
  owner           TEXT NOT NULL,
  tier            TEXT NOT NULL DEFAULT 'standard',
  label           TEXT,
  created_at      BIGINT NOT NULL,
  last_used_at    BIGINT,
  revoked_at      BIGINT
);

--# split

CREATE INDEX IF NOT EXISTS idx_api_keys_owner ON api_keys (owner);

--# split

CREATE TABLE IF NOT EXISTS rate_limit_buckets (
  key_id          TEXT NOT NULL,
  window_start    BIGINT NOT NULL,
  count           BIGINT NOT NULL,
  PRIMARY KEY (key_id, window_start)
);

--# split

-- NUMERIC money columns: the vault handler mutates them in SQL
-- (`SET total_usdc = total_usdc + $n`), which TEXT cannot support.
CREATE TABLE IF NOT EXISTS vaults (
  id                 BIGINT PRIMARY KEY,
  leader             TEXT NOT NULL,
  name               TEXT NOT NULL,
  created_at         BIGINT NOT NULL,
  total_usdc         NUMERIC NOT NULL DEFAULT 0,
  circulating_shares NUMERIC NOT NULL DEFAULT 0,
  hwm_nav            NUMERIC NOT NULL DEFAULT 10000000,
  realized_pnl       NUMERIC NOT NULL DEFAULT 0,
  leader_shares      NUMERIC NOT NULL DEFAULT 0,
  profit_share_bps   INTEGER NOT NULL DEFAULT 1000,
  paused             SMALLINT NOT NULL DEFAULT 0,
  updated_at         BIGINT NOT NULL,
  contract_id        TEXT
);

--# split

CREATE INDEX IF NOT EXISTS idx_vaults_leader ON vaults (leader);

--# split

CREATE INDEX IF NOT EXISTS idx_vaults_created ON vaults (created_at DESC);

--# split

CREATE TABLE IF NOT EXISTS vault_snapshots (
  vault_id        BIGINT NOT NULL,
  ts              BIGINT NOT NULL,
  tvl             NUMERIC NOT NULL,
  nav             NUMERIC NOT NULL,
  open_positions  BIGINT NOT NULL DEFAULT 0,
  hwm             NUMERIC NOT NULL,
  PRIMARY KEY (vault_id, ts)
);

--# split

CREATE INDEX IF NOT EXISTS idx_vault_snapshots_vault ON vault_snapshots (vault_id, ts DESC);

--# split

CREATE TABLE IF NOT EXISTS vault_deposits (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vault_id        BIGINT NOT NULL,
  depositor       TEXT NOT NULL,
  amount          TEXT NOT NULL,
  shares          TEXT NOT NULL,
  ledger          BIGINT NOT NULL,
  ts              BIGINT NOT NULL,
  tx_hash         TEXT NOT NULL,
  event_id        TEXT,
  contract_id     TEXT
);

--# split

CREATE INDEX IF NOT EXISTS idx_vault_deposits_vault ON vault_deposits (vault_id, ts DESC);

--# split

CREATE INDEX IF NOT EXISTS idx_vault_deposits_depositor ON vault_deposits (depositor, ts DESC);

--# split

-- Postgres default NULLS DISTINCT matches SQLite: pre-2026-06 rows with
-- NULL event_id coexist; ON CONFLICT (event_id) ignores NULLs.
CREATE UNIQUE INDEX IF NOT EXISTS uq_vault_deposits_event_id ON vault_deposits (event_id);

--# split

CREATE TABLE IF NOT EXISTS vault_withdraws (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vault_id        BIGINT NOT NULL,
  depositor       TEXT NOT NULL,
  shares          TEXT NOT NULL,
  usdc_out        TEXT NOT NULL,
  ledger          BIGINT NOT NULL,
  ts              BIGINT NOT NULL,
  tx_hash         TEXT NOT NULL,
  event_id        TEXT,
  contract_id     TEXT
);

--# split

CREATE INDEX IF NOT EXISTS idx_vault_withdraws_vault ON vault_withdraws (vault_id, ts DESC);

--# split

CREATE INDEX IF NOT EXISTS idx_vault_withdraws_depositor ON vault_withdraws (depositor, ts DESC);

--# split

CREATE UNIQUE INDEX IF NOT EXISTS uq_vault_withdraws_event_id ON vault_withdraws (event_id);

--# split

CREATE TABLE IF NOT EXISTS vault_fee_claims (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vault_id        BIGINT NOT NULL,
  leader          TEXT NOT NULL,
  amount          TEXT NOT NULL,
  new_nav         TEXT NOT NULL,
  ledger          BIGINT NOT NULL,
  ts              BIGINT NOT NULL,
  tx_hash         TEXT NOT NULL,
  event_id        TEXT,
  contract_id     TEXT
);

--# split

CREATE INDEX IF NOT EXISTS idx_vault_fee_claims_vault ON vault_fee_claims (vault_id, ts DESC);

--# split

CREATE UNIQUE INDEX IF NOT EXISTS uq_vault_fee_claims_event_id ON vault_fee_claims (event_id);

--# split

CREATE TABLE IF NOT EXISTS vault_trades (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vault_id        BIGINT NOT NULL,
  position_id     BIGINT NOT NULL,
  action          TEXT   NOT NULL CHECK (action IN ('open','close')),
  leader          TEXT   NOT NULL,
  collateral      TEXT   NOT NULL DEFAULT '0',
  ledger          BIGINT NOT NULL,
  ts              BIGINT NOT NULL,
  tx_hash         TEXT   NOT NULL,
  pnl             BIGINT,
  contract_id     TEXT,
  UNIQUE (vault_id, position_id, action, tx_hash)
);

--# split

CREATE INDEX IF NOT EXISTS idx_vault_trades_vault_ts ON vault_trades (vault_id, ts DESC);

--# split

CREATE INDEX IF NOT EXISTS idx_vault_trades_action ON vault_trades (vault_id, action);

--# split

-- NUMERIC accumulators: referral handler does `SET x = x + $n`.
CREATE TABLE IF NOT EXISTS referrers (
  referrer                TEXT PRIMARY KEY,
  code                    TEXT NOT NULL UNIQUE,
  created_at              BIGINT NOT NULL,
  referred_count          BIGINT NOT NULL DEFAULT 0,
  total_volume_generated  NUMERIC NOT NULL DEFAULT 0,
  total_earned            NUMERIC NOT NULL DEFAULT 0,
  claimable               NUMERIC NOT NULL DEFAULT 0,
  updated_at              BIGINT NOT NULL,
  contract_id             TEXT
);

--# split

CREATE TABLE IF NOT EXISTS referral_bindings (
  referee     TEXT PRIMARY KEY,
  referrer    TEXT NOT NULL,
  code        TEXT NOT NULL,
  bound_at    BIGINT NOT NULL,
  tx_hash     TEXT NOT NULL,
  contract_id TEXT
);

--# split

CREATE INDEX IF NOT EXISTS idx_referral_bindings_referrer ON referral_bindings (referrer);

--# split

CREATE TABLE IF NOT EXISTS referral_trades (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  referee         TEXT NOT NULL,
  referrer        TEXT NOT NULL,
  original_fee    TEXT NOT NULL,
  discount        TEXT NOT NULL,
  payout          TEXT NOT NULL,
  ledger          BIGINT NOT NULL,
  ts              BIGINT NOT NULL,
  tx_hash         TEXT NOT NULL,
  event_id        TEXT,
  contract_id     TEXT
);

--# split

CREATE INDEX IF NOT EXISTS idx_referral_trades_referrer ON referral_trades (referrer, ts DESC);

--# split

CREATE INDEX IF NOT EXISTS idx_referral_trades_referee ON referral_trades (referee, ts DESC);

--# split

CREATE UNIQUE INDEX IF NOT EXISTS uq_referral_trades_event_id ON referral_trades (event_id);

--# split

CREATE TABLE IF NOT EXISTS referral_claims (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  referrer    TEXT NOT NULL,
  amount      TEXT NOT NULL,
  ledger      BIGINT NOT NULL,
  ts          BIGINT NOT NULL,
  tx_hash     TEXT NOT NULL,
  event_id    TEXT,
  contract_id TEXT
);

--# split

CREATE INDEX IF NOT EXISTS idx_referral_claims_referrer ON referral_claims (referrer, ts DESC);

--# split

CREATE UNIQUE INDEX IF NOT EXISTS uq_referral_claims_event_id ON referral_claims (event_id);

--# split

CREATE TABLE IF NOT EXISTS dead_letter (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id      TEXT   NOT NULL,
  contract_id   TEXT   NOT NULL,
  ledger        BIGINT NOT NULL,
  stage         TEXT   NOT NULL,
  error         TEXT   NOT NULL,
  payload_json  TEXT,
  created_at    BIGINT NOT NULL
);

--# split

CREATE INDEX IF NOT EXISTS idx_dead_letter_event ON dead_letter (event_id);

--# split

CREATE INDEX IF NOT EXISTS idx_dead_letter_stage ON dead_letter (stage, created_at DESC);

--# split

CREATE TABLE IF NOT EXISTS ledger_gaps (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  from_ledger  BIGINT NOT NULL,
  to_ledger    BIGINT NOT NULL,
  reason       TEXT   NOT NULL,
  recorded_at  BIGINT NOT NULL
);

--# split

CREATE INDEX IF NOT EXISTS idx_ledger_gaps_from ON ledger_gaps (from_ledger);

--# split

-- Pre-Supabase web leaderboard baseline (one-time import from the retired
-- Vercel-cron Turso DB; rows before the 2026-07-06T17:00Z prod cutover).
-- total_volume / total_pnl are stored in 7-decimal integer units — the
-- import script scales the legacy USD floats by 1e7 so this table merges
-- with live stats without unit conversion at read time.
CREATE TABLE IF NOT EXISTS leaderboard_legacy (
  address       TEXT PRIMARY KEY,
  trade_count   BIGINT  NOT NULL DEFAULT 0,
  total_volume  NUMERIC NOT NULL DEFAULT 0,
  total_pnl     NUMERIC NOT NULL DEFAULT 0,
  liq_count     BIGINT  NOT NULL DEFAULT 0,
  source        TEXT    NOT NULL DEFAULT 'web-turso-2026-07',
  imported_at   BIGINT  NOT NULL
);
