import { PGlite } from '@electric-sql/pglite';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';

import { isMissingTable, type Db } from '../src/index.js';
import { createPgliteDb } from '../src/pglite.js';

let db: Db;

beforeAll(async () => {
  db = createPgliteDb(new PGlite());
  await db.execute(`CREATE TABLE kv (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    k TEXT NOT NULL UNIQUE,
    v TEXT,
    n BIGINT,
    payload JSONB
  )`);
});

afterAll(async () => {
  await db.close();
});

describe('execute', () => {
  it('inserts with ? args and reports rowsAffected', async () => {
    const res = await db.execute({ sql: 'INSERT INTO kv (k, v) VALUES (?, ?)', args: ['a', '1'] });
    expect(res.rowsAffected).toBe(1);
  });

  it('ON CONFLICT DO NOTHING yields rowsAffected 0 (idempotency guards)', async () => {
    const res = await db.execute({
      sql: 'INSERT INTO kv (k, v) VALUES (?, ?) ON CONFLICT (k) DO NOTHING',
      args: ['a', 'dupe'],
    });
    expect(res.rowsAffected).toBe(0);
  });

  it('CAS-style UPDATE reports rowsAffected like libsql', async () => {
    const miss = await db.execute({ sql: 'UPDATE kv SET v = ? WHERE k = ? AND v = ?', args: ['x', 'a', 'wrong'] });
    expect(miss.rowsAffected).toBe(0);
    const hit = await db.execute({ sql: 'UPDATE kv SET v = ? WHERE k = ? AND v = ?', args: ['2', 'a', '1'] });
    expect(hit.rowsAffected).toBe(1);
  });

  it('returns jsonb as a raw string (production node-pg parity)', async () => {
    await db.execute({
      sql: 'INSERT INTO kv (k, payload) VALUES (?, ?)',
      args: ['json', JSON.stringify({ trader: 'G...X', size: '12345678900000' })],
    });
    const res = await db.execute({ sql: 'SELECT payload FROM kv WHERE k = ?', args: ['json'] });
    const cell = res.rows[0]!.payload;
    expect(typeof cell).toBe('string');
    expect(JSON.parse(String(cell))).toEqual({ trader: 'G...X', size: '12345678900000' });
  });

  it('jsonb ->> extraction works on stored payloads', async () => {
    const res = await db.execute({
      sql: "SELECT payload ->> 'size' AS size FROM kv WHERE k = ?",
      args: ['json'],
    });
    expect(res.rows[0]!.size).toBe('12345678900000');
  });

  it('bigint args are accepted and int8 comes back as a string', async () => {
    await db.execute({ sql: 'INSERT INTO kv (k, n) VALUES (?, ?)', args: ['big', 9007199254740993n] });
    const res = await db.execute({ sql: 'SELECT n FROM kv WHERE k = ?', args: ['big'] });
    expect(String(res.rows[0]!.n)).toBe('9007199254740993');
    expect(BigInt(String(res.rows[0]!.n))).toBe(9007199254740993n);
  });

  it('undefined args are sent as NULL', async () => {
    await db.execute({ sql: 'INSERT INTO kv (k, v) VALUES (?, ?)', args: ['nullish', undefined] });
    const res = await db.execute({ sql: 'SELECT v FROM kv WHERE k = ?', args: ['nullish'] });
    expect(res.rows[0]!.v).toBeNull();
  });

  it('accepts bare string statements', async () => {
    const res = await db.execute('SELECT COUNT(*) AS c FROM kv');
    expect(Number(res.rows[0]!.c)).toBeGreaterThan(0);
  });
});

describe('transaction', () => {
  it('commits atomically', async () => {
    const tx = await db.transaction('write');
    await tx.execute({ sql: 'INSERT INTO kv (k, v) VALUES (?, ?)', args: ['tx1', 'a'] });
    await tx.execute({ sql: 'INSERT INTO kv (k, v) VALUES (?, ?)', args: ['tx2', 'b'] });
    await tx.commit();
    const res = await db.execute("SELECT COUNT(*) AS c FROM kv WHERE k IN ('tx1','tx2')");
    expect(Number(res.rows[0]!.c)).toBe(2);
  });

  it('rolls back cleanly and the pool stays usable', async () => {
    const tx = await db.transaction('write');
    await tx.execute({ sql: 'INSERT INTO kv (k, v) VALUES (?, ?)', args: ['doomed', 'x'] });
    await tx.rollback();
    const res = await db.execute({ sql: 'SELECT COUNT(*) AS c FROM kv WHERE k = ?', args: ['doomed'] });
    expect(Number(res.rows[0]!.c)).toBe(0);
  });

  it('rollback after a failed statement releases the connection (25P02 path)', async () => {
    const tx = await db.transaction('write');
    await expect(tx.execute({ sql: 'INSERT INTO kv (k, v) VALUES (?, ?)', args: ['a', 'dupe-pk'] })).rejects.toThrow();
    await tx.rollback();
    // Pool must not be poisoned:
    const res = await db.execute('SELECT 1 AS one');
    expect(Number(res.rows[0]!.one)).toBe(1);
  });

  it('other work queues behind an open transaction (no interleave deadlock)', async () => {
    const tx = await db.transaction('write');
    await tx.execute({ sql: 'INSERT INTO kv (k, v) VALUES (?, ?)', args: ['lane', '1'] });
    const outside = db.execute({ sql: 'SELECT v FROM kv WHERE k = ?', args: ['lane'] });
    await tx.commit();
    const res = await outside;
    expect(res.rows[0]!.v).toBe('1');
  });
});

describe('batch', () => {
  it('runs statements in one transaction and returns per-statement results', async () => {
    const results = await db.batch(
      [
        { sql: 'INSERT INTO kv (k, v) VALUES (?, ?)', args: ['b1', '1'] },
        { sql: 'UPDATE kv SET v = ? WHERE k = ?', args: ['2', 'b1'] },
      ],
      'write'
    );
    expect(results.map((r) => r.rowsAffected)).toEqual([1, 1]);
  });

  it('is atomic: a failing statement rolls the whole batch back', async () => {
    await expect(
      db.batch([
        { sql: 'INSERT INTO kv (k, v) VALUES (?, ?)', args: ['b2', '1'] },
        { sql: 'INSERT INTO kv (k, v) VALUES (?, ?)', args: ['b2', 'dupe'] },
      ])
    ).rejects.toThrow();
    const res = await db.execute({ sql: 'SELECT COUNT(*) AS c FROM kv WHERE k = ?', args: ['b2'] });
    expect(Number(res.rows[0]!.c)).toBe(0);
  });
});

describe('isMissingTable', () => {
  it('detects pg 42P01', async () => {
    try {
      await db.execute('SELECT * FROM definitely_not_a_table');
      expect.unreachable();
    } catch (err) {
      expect(isMissingTable(err)).toBe(true);
    }
  });

  it('rejects unrelated errors', () => {
    expect(isMissingTable(new Error('syntax error'))).toBe(false);
    expect(isMissingTable(null)).toBe(false);
  });

  it('keeps the legacy libsql message form working', () => {
    expect(isMissingTable(new Error('no such table: events_raw'))).toBe(true);
  });
});
